INSERT INTO post (post_id, post_name, post_email, post_phone, post_position, post_location, post_experience, post_detail, post_notify, post_type, post_salary_min, post_salary_max, post_banner, post_like_count, post_link, post_tags, post_expires, post_created, post_updated) VALUES (1, 'Google Ventures', 'john@doe.com', '09999999999', 'Senior Backend Developer', 'Cebu City', 2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi mattis, lectus vitae faucibus elementum, erat lorem maximus nulla, at condimentum nulla nibh a magna. Donec rutrum magna non mauris sodales pharetra. Duis ullamcorper augue at dolor lacinia sodales. Quisque consectetur magna in justo pulvinar placerat. Etiam eget arcu ut eros auctor porta sed a est. Curabitur sed neque eu sapien interdum vehicula. Aliquam vel finibus eros. Praesent auctor neque luctus, ultricies risus ut, vulputate lacus. Donec commodo elit non mauris congue feugiat. Nam eu purus porta, pulvinar justo vel, tempus augue. Duis rutrum augue justo, at sodales magna euismod nec. Vestibulum vel pretium velit. Cras mollis ligula nec odio tincidunt auctor. Cras faucibus consectetur ullamcorper.', '[\"matches\",\"likes\"]', 'poster', 20000, 40000, '/images/placeholder/banner/banner-1.jpg', 4, 'https://used.com.ph', '[\"IT\", \"Software\"]', '2020-11-10', '2017-10-11 07:28:59', '2017-10-11 07:28:59');

INSERT INTO post (post_id, post_name, post_email, post_phone, post_position, post_location, post_experience, post_detail, post_notify, post_type, post_link, post_expires, post_created, post_updated) VALUES (2, 'Jane Doe', 'jane@doe.com', '555-2525', 'Customer Support', 'Metro Manila', 2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi mattis, lectus vitae faucibus elementum, erat lorem maximus nulla, at condimentum nulla nibh a magna. Donec rutrum magna non mauris sodales pharetra. Duis ullamcorper augue at dolor lacinia sodales. Quisque consectetur magna in justo pulvinar placerat. Etiam eget arcu ut eros auctor porta sed a est. Curabitur sed neque eu sapien interdum vehicula. Aliquam vel finibus eros. Praesent auctor neque luctus, ultricies risus ut, vulputate lacus. Donec commodo elit non mauris congue feugiat. Nam eu purus porta, pulvinar justo vel, tempus augue. Duis rutrum augue justo, at sodales magna euismod nec. Vestibulum vel pretium velit. Cras mollis ligula nec odio tincidunt auctor. Cras faucibus consectetur ullamcorper.', '[\"matches\",\"likes\"]', 'seeker', 'https://used.com.ph', '2020-11-10', '2017-10-11 07:28:59', '2017-10-11 07:28:59');

INSERT INTO post (post_id, post_name, post_email, post_phone, post_position, post_location, post_experience, post_detail, post_notify, post_type, post_salary_min, post_link, post_expires, post_created, post_updated) VALUES (3, 'Google Maps', 'jane@doe.com', '555-2525', 'Customer Support', 'Metro Manila', 2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi mattis, lectus vitae faucibus elementum, erat lorem maximus nulla, at condimentum nulla nibh a magna. Donec rutrum magna non mauris sodales pharetra. Duis ullamcorper augue at dolor lacinia sodales. Quisque consectetur magna in justo pulvinar placerat. Etiam eget arcu ut eros auctor porta sed a est. Curabitur sed neque eu sapien interdum vehicula. Aliquam vel finibus eros. Praesent auctor neque luctus, ultricies risus ut, vulputate lacus. Donec commodo elit non mauris congue feugiat. Nam eu purus porta, pulvinar justo vel, tempus augue. Duis rutrum augue justo, at sodales magna euismod nec. Vestibulum vel pretium velit. Cras mollis ligula nec odio tincidunt auctor. Cras faucibus consectetur ullamcorper.', '[\"matches\",\"likes\"]', 'poster', 15000, 'https://used.com.ph', '2020-11-10', '2017-10-11 07:28:59', '2017-10-11 07:28:59');

INSERT INTO post (post_id, post_name, post_email, post_phone, post_position, post_location, post_experience, post_detail, post_notify, post_type, post_link, post_expires, post_created, post_updated) VALUES (4, 'Jack Doe', 'jack@doe.com', '555-2424', 'Customer Support', 'Metro Manila', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi mattis, lectus vitae faucibus elementum, erat lorem maximus nulla, at condimentum nulla nibh a magna. Donec rutrum magna non mauris sodales pharetra. Duis ullamcorper augue at dolor lacinia sodales. Quisque consectetur magna in justo pulvinar placerat. Etiam eget arcu ut eros auctor porta sed a est. Curabitur sed neque eu sapien interdum vehicula. Aliquam vel finibus eros. Praesent auctor neque luctus, ultricies risus ut, vulputate lacus. Donec commodo elit non mauris congue feugiat. Nam eu purus porta, pulvinar justo vel, tempus augue. Duis rutrum augue justo, at sodales magna euismod nec. Vestibulum vel pretium velit. Cras mollis ligula nec odio tincidunt auctor. Cras faucibus consectetur ullamcorper.', '[\"matches\",\"likes\"]', 'seeker', 'https://used.com.ph', '2020-11-10', '2017-10-11 07:28:59', '2017-10-11 07:28:59');

INSERT INTO post (post_id, post_name, post_email, post_phone, post_position, post_location, post_experience, post_detail, post_notify, post_type, post_salary_min, post_salary_max, post_like_count, post_tags, post_banner, post_link, post_expires, post_created, post_updated) VALUES (5, 'Google Search', 'jack@doe.com', '555-2626', 'Junior Web Developer', 'Metro Manila', 2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi mattis, lectus vitae faucibus elementum, erat lorem maximus nulla, at condimentum nulla nibh a magna. Donec rutrum magna non mauris sodales pharetra. Duis ullamcorper augue at dolor lacinia sodales. Quisque consectetur magna in justo pulvinar placerat. Etiam eget arcu ut eros auctor porta sed a est. Curabitur sed neque eu sapien interdum vehicula. Aliquam vel finibus eros. Praesent auctor neque luctus, ultricies risus ut, vulputate lacus. Donec commodo elit non mauris congue feugiat. Nam eu purus porta, pulvinar justo vel, tempus augue. Duis rutrum augue justo, at sodales magna euismod nec. Vestibulum vel pretium velit. Cras mollis ligula nec odio tincidunt auctor. Cras faucibus consectetur ullamcorper.', '[\"matches\",\"likes\"]', 'poster', 12500, 15000, 4, '[\"IT\", \"Software\"]', '/images/placeholder/banner/banner-1.jpg', 'https://used.com.ph', '2020-11-10', '2017-10-11 07:28:59', '2017-10-11 07:28:59');

INSERT INTO post_profile (post_id, profile_id) VALUES (1, 1), 
(2, 2), 
(3, 2), 
(4, 3), 
(5, 3);