<?php //-->
require_once 'vendor/autoload.php';

//use the cradle function
Cradle\Framework\Decorator::DECORATE;

return cradle()
    //add bootstrap here
    ->preprocess(include('bootstrap/paths.php'))
    ->preprocess(include('bootstrap/debug.php'))
    ->preprocess(include('bootstrap/errors.php'))
    ->preprocess(include('bootstrap/services.php'))
    ->preprocess(include('bootstrap/timezone.php'))
    ->preprocess(include('bootstrap/session.php'))
    ->preprocess(include('bootstrap/i18n.php'))
    ->preprocess(include('bootstrap/roles.php'))
    ->preprocess(include('bootstrap/handlebars.php'))

    //add packages here
    ->register('cblanquera/cradle-handlebars')
    ->register('cblanquera/cradle-queue')
    ->register('cblanquera/cradle-csrf')
    ->register('cblanquera/cradle-captcha')
    ->register('cradlephp/sink-faucet')
    ->register('ezyang/htmlpurifier')
    ->register('/module/currency')
    ->register('/module/tracking')
    ->register('/module/interview')
    ->register('/module/oauth')
    ->register('/module/profile')
    ->register('/module/post')
    ->register('/module/term')
    ->register('/module/crawler')
    ->register('/module/transaction')
    ->register('/module/service')
    ->register('/module/area')
    ->register('/module/research')
    ->register('/module/resume')
    ->register('/module/utility')
    ->register('/module/utm')
    ->register('/module/widget')
    ->register('/module/blog')
    ->register('/module/position')
    ->register('/module/feature')
    ->register('/module/tracer')
    ->register('/module/school')
    ->register('/module/action')
    ->register('/module/campaign')
    ->register('/module/lead')
    ->register('/module/template')
    ->register('/module/action')
    ->register('/module/sms')
    ->register('/module/ses')
    ->register('/module/file')
    ->register('/module/comment')
    ->register('/module/history')
    ->register('/module/sales')
    ->register('/module/gmail')
    ->register('/module/thread')
    ->register('/module/event')
    ->register('/module/school')
    ->register('/module/degree');
