<?php //-->
return [
    'auth-create' => 'Signed Up',
    'auth-forgot' => 'Forgot Password',
    'auth-claim'  => 'Claimed a Profile',
    // 'auth-remove' => 'Login Inactivated',
    // 'auth-restore' => 'Login Reactivated',
    'auth-update' => 'Update Credentials',
    'auth-verify' => 'Verified Email',
    'profile-update' => 'Updated profile',
    'profile-add-achievement' => 'Gained Achievement',
    'profile-add-experience' => 'Gained Experience',
    // 'profile-remove' => 'Profile Inactivated',
    // 'profile-restore' => 'Profile Reactivated',
    'profile-unsubscribe' => 'User Unsubscribed',
    'profile-update-bounce' => 'User Email Bounced',
    'post-create' => 'Created a Post',
    'post-update' => 'Updated a Post',
    // 'post-search' => 'Searched Post',
    'post-download' => 'Downloaded Resume',
    'post-like' => 'Interested a Post',
    'post-view' => 'Viewed a Post',
    'post-notify-like' => 'Notified for a like',
    'post-notify-matches' => 'Notified for matches',
    'post-notify-sms-matches' => ' Notified matched via sms',
    'post-update-email' => 'Updated Email on post',
    'post-update-phone' => 'Updated Phone on post',
    'transaction-create' => 'Buys Credits',
    'achieve-level-10' => 'Achieved Level 10',
    'achieve-level-20' => 'Achieved Level 20',
    'achieve-level-30' => 'Achieved Level 30',
    'achieve-level-40' => 'Achieved Level 40',
    'achieve-level-50' => 'Achieved Level 50'
];
